#!/usr/bin/env ruby

require "biocgem"

require 'erb'
require 'fileutils'
require 'tmpdir'

config = {
  bioc_package_name: 'org.Hs.eg.db',
  bioc_sqlite_database_name: 'org.Hs.eg.sqlite',
  gem_icon: '🧑‍🤝‍🧑',
  gem_constant_name: 'OrgHsEgDb',
  gem_require_name: 'org_hs_eg_db',
  bioc_sqlite_database_sha256sum: 'd22c7e6b13f89488d10bafbf7eacdb6b7aaa697c131ed73f601a502ac86ecd56'
}

target = config[:bioc_package_name]

base = File.expand_path('template/newgem', __dir__)

Dir.mktmpdir do |tmpdir|
  Dir['**/*', base: base].each do |f|
    src = File.expand_path(f, base)
    next unless File.file?(src)

    str = File.read(src)
    erb = ERB.new(str)
    str = erb.result(binding)

    trg = File.expand_path(f, tmpdir)
    fname = File.basename(trg, '.tt')
    fname.gsub!('new_gem_entry', config[:gem_require_name])
    dirname = File.dirname(trg)
    FileUtils.mkdir_p(dirname)
    File.write(File.join(dirname, fname), str)
  end
  FileUtils.cp_r(tmpdir, target)
end
